---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  build:
    image: docker.io/techknowlogick/xgo:go-1.21.x
    commands:
      - ln -s $(pwd) /source
      - make release

  executable:
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - $(find dist/ -executable -type f -iname ${CI_REPO_NAME}-linux-amd64) --help

  changelog:
    image: quay.io/thegeeklab/git-sv
    commands:
      - git fetch --depth=2147483647
      - git sv current-version
      - git sv release-notes -t ${CI_COMMIT_TAG:-next} -o CHANGELOG.md
      - cat CHANGELOG.md

  publish-github:
    image: docker.io/plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - dist/*
      note: CHANGELOG.md
      overwrite: true
      title: ${CI_COMMIT_TAG}
    when:
    - event: [tag]

depends_on:
  - test
